version: '3'

services:
  db:
    container_name: test_db
    image: postgres:latest
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    networks:
      - service

  redis:
    container_name: test_redis
    image: redis:latest
    env_file:
      - .env
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    networks:
      - service

  drf:
    container_name: test_api
    build:
      context: .
    command: >
             sh -c "
             python src/manage.py makemigrations &&
             python src/manage.py migrate &&
             pytest -v src/api/tests"
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - service
    restart: always
    depends_on:
      - db
      - redis


networks:
  service:
    driver: bridge